<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>EasySave</AssemblyName>
    <RootNamespace>EasySave</RootNamespace>
    <Version>1.0.0</Version>
    <LangVersion>7.3</LangVersion>
    <AutomaticallyUseReferenceAssemblyPackages>false</AutomaticallyUseReferenceAssemblyPackages>

    <BepInExRoot Condition="'$(BepInExRoot)' == ''">$(HOME)/.config/r2modmanPlus-local/EasyDeliveryCo/profiles/dev/BepInEx</BepInExRoot>
    <GameManagedRoot Condition="'$(GameManagedRoot)' == ''">$(HOME)/.steam/steam/steamapps/common/Easy Delivery Co/EasyDeliveryCo_Data/Managed</GameManagedRoot>
    <FrameworkPathOverride Condition="'$(OS)' != 'Windows_NT' and '$(FrameworkPathOverride)' == '' and Exists('/usr/lib/mono/4.7.2-api')">/usr/lib/mono/4.7.2-api</FrameworkPathOverride>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="netstandard">
      <HintPath>$(GameManagedRoot)/netstandard.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(BepInExRoot)/core/BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(BepInExRoot)/core/0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(GameManagedRoot)/UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GameManagedRoot)/UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(GameManagedRoot)/UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(GameManagedRoot)/UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(GameManagedRoot)/UnityEngine.UIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(GameManagedRoot)/UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
